name: iOS Build and Upload to Appetize

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.4.0' # Adjust to your Xcode version

    - name: Build the app
      run: |
        xcodebuild -workspace SnoreBuddy.xcworkspace -scheme SnoreBuddy -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12,OS=15.2' build

    - name: Archive the app
      run: |
        xcodebuild -workspace SnoreBuddy.xcworkspace -scheme SnoreBuddy -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12,OS=15.2' archive -archivePath $PWD/build/SnoreBuddy.xcarchive

    - name: Export the app
      run: |
        xcodebuild -exportArchive -archivePath $PWD/build/SnoreBuddy.xcarchive -exportOptionsPlist ExportOptions.plist -exportPath $PWD/build

    - name: Zip the app
      run: |
        cd build
        zip -r SnoreBuddy.zip SnoreBuddy.app

    - name: Upload to Appetize.io
      env:
        APPETIZE_API_TOKEN: ${{ secrets.APPETIZE_API_TOKEN }}
      run: |
        curl https://api.appetize.io/v1/apps -F "file=@build/SnoreBuddy.zip" -F "platform=ios" -F "token=${APPETIZE_API_TOKEN}"
